import { Lead, Client, Meeting, Project, Task, DocumentItem, Proposal, Invoice, DashboardStats, AIInsight, User } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    name: 'Sarah Jenkins',
    email: 's.jenkins@archicorp-cfo.com',
    role: 'PARTNER',
    title: 'Managing Partner & Senior CFO Consultant',
    department: 'Executive Practice',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 'u-2',
    name: 'Michael Chen',
    email: 'm.chen@archicorp-cfo.com',
    role: 'SENIOR_CONSULTANT',
    title: 'Partner - Corporate Restructuring',
    department: 'Financial Advisory',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 'u-3',
    name: 'Robert Black',
    email: 'r.black@archicorp-cfo.com',
    role: 'FINANCIAL_ANALYST',
    title: 'Lead M&A Financial Analyst',
    department: 'Valuation & Modeling',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=150&q=80',
  },
];

export const INITIAL_DASHBOARD_STATS: DashboardStats = {
  totalAssetsUnderMgmt: '$1.24B',
  assetsGrowthQuarterly: '+12.4%',
  billableRatio: '84.2%',
  billableRatioTarget: '85.0%',
  activePipelineValue: '$42.8M',
  pendingDealsCount: 14,
  activeEngagementsCount: 18,
  totalClientsCount: 32,
  monthlyRecurringRevenue: 345000,
  pendingInvoicesAmount: 128500,
};

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    leadOwner: 'Sarah Jenkins',
    assignedEmployee: 'Sarah Jenkins',
    assignedPartner: 'Sarah Jenkins',
    company: 'Starlight BioTech Corp',
    companyName: 'Starlight BioTech Corp',
    contactPerson: 'Dr. Marcus Vance',
    contactName: 'Dr. Marcus Vance',
    email: 'm.vance@starlightbio.io',
    contactEmail: 'm.vance@starlightbio.io',
    phone: '+1 (555) 389-2210',
    contactPhone: '+1 (555) 389-2210',
    industry: 'Healthcare & Biotech',
    priority: 'HIGH',
    status: 'PROPOSAL_SENT',
    stage: 'PROPOSAL_SENT',
    leadSource: 'Inbound Partner Referral',
    source: 'Inbound Partner Referral',
    expectedRevenue: 650000,
    estimatedValue: 650000,
    probability: 75,
    followUpDate: '2026-08-12',
    timeline: 'Q3 2026',
    aiScore: 88,
    aiRecommendation: 'High conversion likelihood. Client responded positively to M&A audit framework.',
    meetingHistory: [
      { id: 'mh-1', date: '2026-07-18', title: 'Initial Discovery & R&D Review', summary: 'Reviewed Series C valuation expectations and fractional CFO requirements.', organizer: 'Sarah Jenkins' },
      { id: 'mh-2', date: '2026-07-28', title: 'Proposal Deep Dive', summary: 'Walked through tax optimization roadmap with Dr. Vance.', organizer: 'Sarah Jenkins' }
    ],
    proposalHistory: [
      { id: 'ph-1', date: '2026-07-30', title: 'Fractional CFO Advisory Proposal v1', amount: 650000, status: 'PROPOSAL_SENT' }
    ],
    leadNotes: 'Requires Series C financial modeling, R&D tax credit optimization, and interim CFO advisory.',
    notes: 'Requires Series C financial modeling, R&D tax credit optimization, and interim CFO advisory.',
    createdAt: '2026-07-15'
  },
  {
    id: 'lead-102',
    leadOwner: 'Alex Rivera',
    assignedEmployee: 'Michael Chen',
    assignedPartner: 'Michael Chen',
    company: 'Atlas Capital Holdings',
    companyName: 'Atlas Capital Holdings',
    contactPerson: 'Eleanor Vance',
    contactName: 'Eleanor Vance',
    email: 'evance@atlascap.com',
    contactEmail: 'evance@atlascap.com',
    phone: '+1 (555) 902-1144',
    contactPhone: '+1 (555) 902-1144',
    industry: 'Private Equity & Real Estate',
    priority: 'HIGH',
    status: 'QUALIFIED',
    stage: 'QUALIFIED',
    leadSource: 'Executive Networking',
    source: 'Executive Networking',
    expectedRevenue: 1200000,
    estimatedValue: 1200000,
    probability: 85,
    followUpDate: '2026-08-15',
    timeline: '1 Month',
    aiScore: 92,
    aiRecommendation: 'Key decision maker confirmed budget. Prepare secondary fee structure options.',
    meetingHistory: [
      { id: 'mh-3', date: '2026-07-10', title: 'Portfolio Restructuring Consultation', summary: 'Discussed $800M portfolio advisory scope with Eleanor Vance.', organizer: 'Michael Chen' }
    ],
    proposalHistory: [
      { id: 'ph-2', date: '2026-07-14', title: 'Private Equity Restructuring SLA', amount: 1200000, status: 'UNDER_REVIEW' }
    ],
    leadNotes: 'Looking for full-scope fractional CFO advisory for $800M portfolio restructuring.',
    notes: 'Looking for full-scope fractional CFO advisory for $800M portfolio restructuring.',
    createdAt: '2026-07-02'
  },
  {
    id: 'lead-103',
    leadOwner: 'Sarah Jenkins',
    assignedEmployee: 'Robert Black',
    assignedPartner: 'Robert Black',
    company: 'NexGen Cloud Solutions',
    companyName: 'NexGen Cloud Solutions',
    contactPerson: 'David Sterling',
    contactName: 'David Sterling',
    email: 'd.sterling@nexgencloud.net',
    contactEmail: 'd.sterling@nexgencloud.net',
    phone: '+1 (555) 471-8822',
    contactPhone: '+1 (555) 471-8822',
    industry: 'SaaS Technology',
    priority: 'MEDIUM',
    status: 'MEETING_SCHEDULED',
    stage: 'MEETING_SCHEDULED',
    leadSource: 'Cold Outreach',
    source: 'Cold Outreach',
    expectedRevenue: 480000,
    estimatedValue: 480000,
    probability: 50,
    followUpDate: '2026-08-10',
    timeline: '2 Months',
    aiScore: 68,
    aiRecommendation: 'Demonstrate benchmark comparison chart during presentation to highlight revenue leakages.',
    meetingHistory: [
      { id: 'mh-4', date: '2026-08-08', title: 'ASC 606 Revenue Recognition Pitch', summary: 'Scheduled demo call to show SaaS benchmarking engine.', organizer: 'Robert Black' }
    ],
    proposalHistory: [],
    leadNotes: 'ARR scale from $10M to $50M. Needs SaaS metric benchmarking and ASC 606 revenue recognition.',
    notes: 'ARR scale from $10M to $50M. Needs SaaS metric benchmarking and ASC 606 revenue recognition.',
    createdAt: '2026-07-20'
  },
  {
    id: 'lead-104',
    leadOwner: 'Alex Rivera',
    assignedEmployee: 'Sarah Jenkins',
    assignedPartner: 'Sarah Jenkins',
    company: 'Pinnacle Supply Networks',
    companyName: 'Pinnacle Supply Networks',
    contactPerson: 'Arthur Pendelton',
    contactName: 'Arthur Pendelton',
    email: 'apendelton@pinnaclesupply.com',
    contactEmail: 'apendelton@pinnaclesupply.com',
    phone: '+1 (555) 782-9900',
    contactPhone: '+1 (555) 782-9900',
    industry: 'Logistics & Distribution',
    priority: 'LOW',
    status: 'NEW',
    stage: 'NEW',
    leadSource: 'Website Inquiry',
    source: 'Website Inquiry',
    expectedRevenue: 350000,
    estimatedValue: 350000,
    probability: 30,
    followUpDate: '2026-08-18',
    timeline: 'Q4 2026',
    aiScore: 45,
    aiRecommendation: 'Schedule discovery call focusing on working capital ratios and inventory turn optimization.',
    meetingHistory: [],
    proposalHistory: [],
    leadNotes: 'Initial discussion around working capital audit and cash flow forecasting models.',
    notes: 'Initial discussion around working capital audit and cash flow forecasting models.',
    createdAt: '2026-07-28'
  },
  {
    id: 'lead-105',
    leadOwner: 'Sarah Jenkins',
    assignedEmployee: 'Sarah Jenkins',
    assignedPartner: 'Sarah Jenkins',
    company: 'Apex Quantum Dynamics',
    companyName: 'Apex Quantum Dynamics',
    contactPerson: 'Elena Rostova',
    contactName: 'Elena Rostova',
    email: 'elena@quantumdynamics.io',
    contactEmail: 'elena@quantumdynamics.io',
    phone: '+1 (555) 991-0023',
    contactPhone: '+1 (555) 991-0023',
    industry: 'DeepTech / Hardware',
    priority: 'HIGH',
    status: 'NEGOTIATION',
    stage: 'NEGOTIATION',
    leadSource: 'Partner Referral',
    source: 'Partner Referral',
    expectedRevenue: 890000,
    estimatedValue: 890000,
    probability: 70,
    followUpDate: '2026-08-14',
    timeline: '3 Weeks',
    aiScore: 81,
    aiRecommendation: 'Schedule preliminary data room review before pitch.',
    meetingHistory: [
      { id: 'mh-5', date: '2026-07-26', title: 'Data Room & Series B Audit Review', summary: 'Aligned on compliance terms for Series B $35M raise.', organizer: 'Sarah Jenkins' }
    ],
    proposalHistory: [
      { id: 'ph-3', date: '2026-08-01', title: 'Audit Defense & CFO Retainer', amount: 890000, status: 'NEGOTIATION' }
    ],
    leadNotes: 'Preparing for Series B $35M capital raise. Audit defense required.',
    notes: 'Preparing for Series B $35M capital raise. Audit defense required.',
    createdAt: '2026-07-24'
  },
  {
    id: 'lead-106',
    leadOwner: 'Sarah Jenkins',
    assignedEmployee: 'Sarah Jenkins',
    assignedPartner: 'Sarah Jenkins',
    company: 'Vanguard Energy Partners',
    companyName: 'Vanguard Energy Partners',
    contactPerson: 'Victoria Sterling',
    contactName: 'Victoria Sterling',
    email: 'v.sterling@vanguardep.com',
    contactEmail: 'v.sterling@vanguardep.com',
    phone: '+1 (555) 782-9900',
    contactPhone: '+1 (555) 782-9900',
    industry: 'CleanTech & Energy',
    priority: 'HIGH',
    status: 'WON',
    stage: 'WON',
    leadSource: 'Executive Referral',
    source: 'Executive Referral',
    expectedRevenue: 950000,
    estimatedValue: 950000,
    probability: 100,
    followUpDate: '2026-08-20',
    timeline: 'Executed',
    aiScore: 94,
    aiRecommendation: 'Contract executed via DocuSign.',
    meetingHistory: [
      { id: 'mh-6', date: '2026-07-29', title: 'Final Contract Sign-off', summary: 'Executed MSA agreement for fractional CFO retainer.', organizer: 'Sarah Jenkins' }
    ],
    proposalHistory: [
      { id: 'ph-4', date: '2026-08-02', title: 'Master Services Agreement (MSA)', amount: 950000, status: 'EXECUTED' }
    ],
    leadNotes: 'Master Services Agreement (MSA) & Fractional CFO contract executed.',
    notes: 'Master Services Agreement (MSA) & Fractional CFO contract executed.',
    createdAt: '2026-07-28',
    contractType: 'Master Services Agreement (MSA)',
    contractStatus: 'EXECUTED'
  }
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-01',
    name: 'Meridian Real Estate Holdings',
    code: 'MRE-01',
    industry: 'Commercial Real Estate',
    monthlyRetainer: 45000,
    totalAssetsUnderMgmt: 450000000,
    status: 'ACTIVE',
    slaLevel: 'PLATINUM',
    leadPartner: 'Sarah Jenkins',
    contactPerson: 'Julia Thorne (VP Finance)',
    email: 'j.thorne@meridianre.com',
    phone: '+1 (555) 234-5678',
    activeEngagementsCount: 3,
    healthScore: 'EXCELLENT',
    onboardedDate: '2024-03-15',
  },
  {
    id: 'cli-02',
    name: 'Global Logistics Corp',
    code: 'GLC-02',
    industry: 'Supply Chain & Transport',
    monthlyRetainer: 75000,
    totalAssetsUnderMgmt: 620000000,
    status: 'ACTIVE',
    slaLevel: 'PLATINUM',
    leadPartner: 'Michael Chen',
    contactPerson: 'Arthur Vance (CFO)',
    email: 'avance@globallogistics.com',
    phone: '+1 (555) 876-5432',
    activeEngagementsCount: 2,
    healthScore: 'EXCELLENT',
    onboardedDate: '2023-11-01',
  },
  {
    id: 'cli-03',
    name: 'Vanguard Fintech Solutions',
    code: 'VFS-03',
    industry: 'Financial Technology',
    monthlyRetainer: 60000,
    totalAssetsUnderMgmt: 180000000,
    status: 'ACTIVE',
    slaLevel: 'GOLD',
    leadPartner: 'Sarah Jenkins',
    contactPerson: 'Samantha Reed (CEO)',
    email: 'sreed@vanguardfintech.io',
    phone: '+1 (555) 345-6789',
    activeEngagementsCount: 2,
    healthScore: 'NEEDS_ATTENTION',
    onboardedDate: '2025-01-10',
  },
  {
    id: 'cli-04',
    name: 'Horizon Healthcare Group',
    code: 'HHG-04',
    industry: 'Healthcare Providers',
    monthlyRetainer: 50000,
    totalAssetsUnderMgmt: 290000000,
    status: 'ACTIVE',
    slaLevel: 'GOLD',
    leadPartner: 'Robert Black',
    contactPerson: 'Dr. Gregory House (COO)',
    email: 'ghouse@horizonhealth.org',
    phone: '+1 (555) 987-6543',
    activeEngagementsCount: 1,
    healthScore: 'GOOD',
    onboardedDate: '2025-05-20',
  },
];

export const INITIAL_MEETINGS: Meeting[] = [
  {
    id: 'meet-201',
    title: 'Q3 Board Financial Strategy & Capital Structure Review',
    clientName: 'Meridian Real Estate Holdings',
    meetingDate: '2026-08-03',
    startTime: '10:00 AM',
    endTime: '11:30 AM',
    type: 'BOARD_PRESENTATION',
    status: 'SCHEDULED',
    location: 'Executive Boardroom / Zoom (Hybrid)',
    attendees: ['Sarah Jenkins', 'Julia Thorne', 'CEO Harrison Ford'],
    agenda: '1. Review Q2 Debt Service Coverage Ratio\n2. Refinancing proposal for $120M Commercial Bond\n3. Tax strategy update',
    summaryNotes: 'Pre-meeting alignment completed with VP of Finance. Slide deck updated with debt sensitivity matrix.',
    aiActionItems: [
      'Finalize 10-year cash flow sensitivity model by Friday',
      'Send revised bond covenant summary to Board Secretary',
    ],
  },
  {
    id: 'meet-202',
    title: 'Post-Merger Financial Integration & Accounting Sync',
    clientName: 'Global Logistics Corp',
    meetingDate: '2026-08-04',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    type: 'STRATEGY_REVIEW',
    status: 'SCHEDULED',
    location: 'Global Logistics HQ (Chicago)',
    attendees: ['Michael Chen', 'Arthur Vance', 'IT Director Kenneth Smith'],
    agenda: '1. ERP migration milestones for ERP 2.0\n2. Consolidated revenue recognition rules\n3. Audit trail validation',
    summaryNotes: 'Focus on SAP to NetSuite general ledger data mapping.',
  },
  {
    id: 'meet-203',
    title: 'Regulatory Audit & SOC-2 Financial Controls Review',
    clientName: 'Vanguard Fintech Solutions',
    meetingDate: '2026-07-30',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    type: 'AUDIT_PREP',
    status: 'COMPLETED',
    location: 'Microsoft Teams',
    attendees: ['Sarah Jenkins', 'Samantha Reed', 'Audit Lead Tom Blake'],
    agenda: '1. Evaluation of internal payroll controls\n2. Review of liquidity buffers\n3. Response to SEC inquiry draft',
    summaryNotes: 'Control deficiencies identified in wire approval policy. Recommended dual-authorization matrix.',
    aiActionItems: [
      'Draft updated Dual-Authorization Wire Policy document',
      'Provide liquidity risk matrix for Q3 SEC filing',
    ],
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-301',
    name: 'Meridian Portfolio Refinancing & Capital Restructuring',
    code: 'ENG-2026-08',
    clientName: 'Meridian Real Estate Holdings',
    clientId: 'cli-01',
    leadManager: 'Sarah Jenkins',
    budget: 450000,
    spentBudget: 280000,
    startDate: '2026-03-01',
    targetEndDate: '2026-09-30',
    status: 'IN_PROGRESS',
    completionPercentage: 68,
    description: 'Full-scope financial advisory to restructure $120M debt portfolio across 14 commercial real estate assets.',
    milestones: [
      { id: 'm-1', title: 'Asset Valuation & Debt Audit', dueDate: '2026-04-15', completed: true },
      { id: 'm-2', title: 'Lender Term Sheet Negotiation', dueDate: '2026-06-30', completed: true },
      { id: 'm-3', title: 'Board Capital Approval', dueDate: '2026-08-15', completed: false },
      { id: 'm-4', title: 'Refinancing Closing & Escrow Distribution', dueDate: '2026-09-30', completed: false },
    ],
  },
  {
    id: 'proj-302',
    name: 'Global Logistics Cross-Border ERP & Tax Alignment',
    code: 'ENG-2026-12',
    clientName: 'Global Logistics Corp',
    clientId: 'cli-02',
    leadManager: 'Michael Chen',
    budget: 1200000,
    spentBudget: 740000,
    startDate: '2026-01-15',
    targetEndDate: '2026-11-30',
    status: 'IN_PROGRESS',
    completionPercentage: 62,
    description: 'Optimizing international transfer pricing and implementing ERP financial reporting across 12 countries.',
    milestones: [
      { id: 'm-201', title: 'Transfer Pricing Country Study', dueDate: '2026-03-31', completed: true },
      { id: 'm-202', title: 'SAP NetSuite Ledger Synchronization', dueDate: '2026-07-31', completed: true },
      { id: 'm-203', title: 'Global Tax Regulatory Filing', dueDate: '2026-10-15', completed: false },
    ],
  },
  {
    id: 'proj-303',
    name: 'Vanguard Series B Due Diligence & Valuation Model',
    code: 'ENG-2026-19',
    clientName: 'Vanguard Fintech Solutions',
    clientId: 'cli-03',
    leadManager: 'Sarah Jenkins',
    budget: 850000,
    spentBudget: 590000,
    startDate: '2026-04-01',
    targetEndDate: '2026-08-31',
    status: 'IN_PROGRESS',
    completionPercentage: 75,
    description: 'Financial model construction, SaaS Cohort Retention analysis, and investor data room preparation.',
    milestones: [
      { id: 'm-301', title: 'Historical Cohort LTV/CAC Audit', dueDate: '2026-05-15', completed: true },
      { id: 'm-302', title: 'DCF & Multiple Valuation Model', dueDate: '2026-06-30', completed: true },
      { id: 'm-303', title: 'Lead Investor Data Room Setup', dueDate: '2026-08-15', completed: false },
    ],
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-401',
    title: 'Audit Meridian Q2 Debt Covenant Compliance Certificate',
    projectName: 'Meridian Portfolio Refinancing & Capital Restructuring',
    clientName: 'Meridian Real Estate Holdings',
    assignee: 'Robert Black',
    dueDate: '2026-08-02',
    status: 'IN_PROGRESS',
    priority: 'URGENT',
    estimatedHours: 12,
    loggedHours: 8,
    description: 'Verify DSCR exceeds 1.35x across all sub-entities before Board mailing.',
  },
  {
    id: 'task-402',
    title: 'Draft Vanguard Fintech 5-Year DCF Financial Model',
    projectName: 'Vanguard Series B Due Diligence & Valuation Model',
    clientName: 'Vanguard Fintech Solutions',
    assignee: 'Robert Black',
    dueDate: '2026-08-05',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    estimatedHours: 25,
    loggedHours: 18,
    description: 'Incorporate 15% annual churn scenarios and net retention rate calculations.',
  },
  {
    id: 'task-403',
    title: 'Prepare Global Logistics Cross-Border Transfer Pricing Memorandum',
    projectName: 'Global Logistics Cross-Border ERP & Tax Alignment',
    clientName: 'Global Logistics Corp',
    assignee: 'Michael Chen',
    dueDate: '2026-08-10',
    status: 'BACKLOG',
    priority: 'MEDIUM',
    estimatedHours: 16,
    loggedHours: 0,
    description: 'Review OECD pillar two compliance impact on EU operations.',
  },
  {
    id: 'task-404',
    title: 'Conduct Monthly Client Billable Time Ratio Audit',
    projectName: 'Practice Executive Operations',
    clientName: 'Archicorp Practice',
    assignee: 'Sarah Jenkins',
    dueDate: '2026-07-31',
    status: 'IN_REVIEW',
    priority: 'HIGH',
    estimatedHours: 6,
    loggedHours: 5,
    description: 'Cross-check partner billable hours against monthly retainers.',
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-501',
    title: 'Meridian_Refinancing_Debt_Covenant_Model_v3.4.xlsx',
    category: 'FINANCIAL_MODEL',
    clientName: 'Meridian Real Estate Holdings',
    uploadedBy: 'Robert Black',
    uploadDate: '2026-07-25',
    fileSize: '14.8 MB',
    fileType: 'Excel Spreadsheet',
    version: 'v3.4',
    aiSummary: 'Includes 3 scenario forecasts for interest rate changes (+/- 100 bps) and sensitivity matrix on debt service ratio.',
  },
  {
    id: 'doc-502',
    title: 'Global_Logistics_Master_Engagement_Agreement_Signed.pdf',
    category: 'CONTRACT',
    clientName: 'Global Logistics Corp',
    uploadedBy: 'Sarah Jenkins',
    uploadDate: '2026-01-14',
    fileSize: '4.2 MB',
    fileType: 'PDF Document',
    version: 'v1.0 Final',
    aiSummary: 'Master consulting agreement signed for 24 months with $75k monthly retainer and performance bonus clause.',
  },
  {
    id: 'doc-503',
    title: 'Vanguard_Fintech_Series_B_Valuation_Report_Draft.docx',
    category: 'PROPOSAL_DOC',
    clientName: 'Vanguard Fintech Solutions',
    uploadedBy: 'Robert Black',
    uploadDate: '2026-07-28',
    fileSize: '8.6 MB',
    fileType: 'Word Document',
    version: 'v2.1',
    aiSummary: 'Estimated pre-money valuation range of $140M - $165M based on 11.2x ARR multiple and discounted cash flows.',
  },
  {
    id: 'doc-504',
    title: 'Horizon_Healthcare_IRS_Tax_Audit_Defense_Memo.pdf',
    category: 'TAX_FILING',
    clientName: 'Horizon Healthcare Group',
    uploadedBy: 'Michael Chen',
    uploadDate: '2026-06-12',
    fileSize: '3.1 MB',
    fileType: 'PDF Document',
    version: 'v1.2',
    aiSummary: 'Formal defense documentation confirming eligibility for $1.8M R&D tax credit claims.',
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-601',
    proposalNumber: 'PROP-2026-089',
    title: 'Fractional CFO Advisory & Series C Preparation',
    clientName: 'Starlight BioTech Corp',
    contactEmail: 'm.vance@starlightbio.io',
    status: 'SENT',
    validUntil: '2026-08-31',
    createdDate: '2026-07-18',
    totalAmount: 185000,
    executiveSummary: 'Archicorp Practice will provide executive CFO leadership, valuation modeling, and lead investor negotiation support for Starlight BioTech.',
    scopeOfWork: 'Phase 1: Financial Model Restructuring (Month 1-2)\nPhase 2: Investor Data Room & Cap Table Audit (Month 3)\nPhase 3: Series C Term Sheet Advisory (Month 4-6)',
    preparedBy: 'Sarah Jenkins',
    items: [
      { id: 'pi-1', description: 'Executive CFO Partner Retainer (6 Months)', hoursOrUnits: 6, rate: 25000, total: 150000 },
      { id: 'pi-2', description: 'Comprehensive DCF & Valuation Modeling', hoursOrUnits: 70, rate: 350, total: 24500 },
      { id: 'pi-3', description: 'Data Room Compliance Setup', hoursOrUnits: 30, rate: 350, total: 10500 },
    ],
  },
  {
    id: 'prop-602',
    proposalNumber: 'PROP-2026-092',
    title: 'Working Capital & Inventory Cash Flow Optimization',
    clientName: 'Pinnacle Supply Networks',
    contactEmail: 'apendelton@pinnaclesupply.com',
    status: 'DRAFT',
    validUntil: '2026-09-15',
    createdDate: '2026-07-29',
    totalAmount: 95000,
    executiveSummary: 'Comprehensive working capital audit to release $8M-$12M in trapped operating cash flow across 5 logistics hubs.',
    scopeOfWork: '1. Inventory Turn Rate Analysis\n2. Accounts Receivable Collections Framework\n3. Cash Conversion Cycle Reduction Plan',
    preparedBy: 'Michael Chen',
    items: [
      { id: 'pi-10', description: 'Working Capital Audit & Diagnostic', hoursOrUnits: 1, rate: 45000, total: 45000 },
      { id: 'pi-11', description: 'Treasury & AR System Implementation', hoursOrUnits: 1, rate: 50000, total: 50000 },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-701',
    invoiceNumber: 'INV-2026-044',
    clientName: 'Meridian Real Estate Holdings',
    clientId: 'cli-01',
    issueDate: '2026-07-01',
    dueDate: '2026-07-31',
    status: 'PAID',
    subtotal: 45000,
    tax: 0,
    totalAmount: 45000,
    notes: 'July 2026 Fractional CFO & Refinancing Advisory Retainer',
    items: [
      { id: 'ii-1', serviceDescription: 'Monthly Retainer - Executive CFO & Debt Advisory Services', amount: 45000 },
    ],
  },
  {
    id: 'inv-702',
    invoiceNumber: 'INV-2026-045',
    clientName: 'Global Logistics Corp',
    clientId: 'cli-02',
    issueDate: '2026-07-01',
    dueDate: '2026-07-31',
    status: 'PENDING',
    subtotal: 75000,
    tax: 0,
    totalAmount: 75000,
    notes: 'July 2026 ERP Implementation & Cross-Border Tax Advisory',
    items: [
      { id: 'ii-2', serviceDescription: 'Monthly Retainer - ERP Integration & Transfer Pricing', amount: 75000 },
    ],
  },
  {
    id: 'inv-703',
    invoiceNumber: 'INV-2026-046',
    clientName: 'Vanguard Fintech Solutions',
    clientId: 'cli-03',
    issueDate: '2026-06-15',
    dueDate: '2026-07-15',
    status: 'OVERDUE',
    subtotal: 53500,
    tax: 0,
    totalAmount: 53500,
    notes: 'Series B Valuation Modeling Phase 2 Deliverable Milestone',
    items: [
      { id: 'ii-3', serviceDescription: 'DCF Model Delivery & Investor Data Room Prep', amount: 53500 },
    ],
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai-1',
    type: 'FORECAST',
    title: 'Capacity Shortfall in Q3 Financial Modeling',
    description: 'Current billable workload trends suggest a 14% analyst capacity deficit in Q3. Recommendation: Fast-track recruitment of 2 Senior M&A Analysts.',
    actionableLabel: 'Review Resource Allocation',
    timestamp: '10 mins ago',
  },
  {
    id: 'ai-2',
    type: 'OPPORTUNITY',
    title: 'Unused Scope Upsell Identified for Meridian',
    description: 'Meridian Real Estate engagement has 20% unallocated budget capacity. Recommendation: Propose tax credit audit module ($65,000 value).',
    actionableLabel: 'Draft Upsell Proposal',
    timestamp: '1 hour ago',
  },
  {
    id: 'ai-3',
    type: 'ALERT',
    title: 'Invoice Overdue Notice: Vanguard Fintech',
    description: 'Invoice INV-2026-046 ($53,500) is 16 days past due. Automatic email reminder draft prepared for Managing Partner review.',
    actionableLabel: 'Send Overdue Reminder',
    timestamp: '2 hours ago',
  },
];
